spring:
  security:
    oauth2:
      resourceserver:
         jwt:
             issuer-uri: http://localhost:8080/realms/springBootKC
             jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: springBootKC
  auth-server-url: http://localhost:8080/auth
  public-client: true
  bearer-only: true